# Use an official Python runtime as a parent image
FROM python:3.8-slim AS python-builder

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the 'main' directory into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r main/requirements.txt

# Use an official Node.js runtime as a parent image
FROM node:14 AS node-builder

# Set the working directory to /app
WORKDIR /app

# Copy only the necessary files for Node.js
COPY package.json package-lock.json /app/

# Install Node.js dependencies
RUN npm install

# Copy the remaining files from the Python builder stage
COPY --from=python-builder /app /app

# Copy the .env file into the image
COPY .env /app/.env

# Make port 80 available to the world outside this container
EXPOSE 80


# Run app.py when the container launches
CMD ["python", "main/main.py"]
